version: '3.8'

services:
  flask:
    build: ./app
    container_name: flask
    image: ncoy/flask-blog:latest
    command: sh start.sh
    volumes:
      - ${PWD}/app/flask_blog/static/profile_pics:/usr/src/app/app/flask_blog/static/profile_pics
      - ${PWD}/app/instance:/usr/src/app/app/instance
    networks:
      my-network:
        aliases:
          - flask-app
    env_file:
      - .env
  nginx:
    build: ./nginx
    image: ncoy/flask_tutorial-nginx:latest
    container_name: nginx
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask

networks:
  my-network: