version: '3.8'

services:
  db:
    image: postgres:13-alpine
    hostname: db
    container_name: postgres
    env_file:
      - ../../.env
    volumes:
      - ../.././postgres_data:/var/lib/postgresql/data
    networks:
      - my-network
  flask:
    build: ../../.
    container_name: flask
    image: ncoy/flask-blog:latest
    command: sh start.sh
    volumes:
      - ../.././app/flask_blog/static/profile_pics:/usr/src/app/app/flask_blog/static/profile_pics
      - ../.././app/instance:/usr/src/app/app/instance
      - ../.././pgloader/:/usr/src/app/app/pgloader
    networks:
      my-network:
        aliases:
          - flask-app
    env_file:
      - ../../.env
    depends_on:
      - db
  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../.././nginx/nginx_dev/:/etc/nginx/conf.d/:ro
      - ../.././app/flask_blog/static/:/home/app/web/project/static
      - ../.././letsencrypt/:/letsencrypt
      - ../.././letsencrypt/certs/:/etc/letsencrypt
    networks:
      - my-network
    depends_on:
      - flask

networks:
  my-network: