version: '3.8'

services:
  flask:
    build: ../../.
    container_name: flask
    image: ncoy/flask-blog:latest
    command: sh start.sh
    volumes:
      - ../.././app/flask_blog/static/profile_pics:/usr/src/app/app/flask_blog/static/profile_pics
      - ../.././app/instance:/usr/src/app/app/instance
    networks:
      my-network:
        aliases:
          - flask-app
    env_file:
      - ../../.env
  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../.././nginx/nginx_dev/:/etc/nginx/conf.d/:ro
      - ../.././app/flask_blog/static/:/home/app/web/project/static
    networks:
      - my-network
    depends_on:
      - flask

networks:
  my-network: